# Generated by Django 5.0.3 on 2024-03-09 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='', max_length=200)),
                ('student_id', models.CharField(default='', max_length=200)),
                ('preferred_start_date', models.DateField(default=datetime.datetime(2024, 3, 9, 13, 26, 36, 266470, tzinfo=datetime.timezone.utc))),
                ('preferred_end_date', models.DateField(default=datetime.datetime(2024, 3, 9, 13, 26, 36, 266481, tzinfo=datetime.timezone.utc))),
                ('appointment_id', models.CharField(blank=True, default='', max_length=200)),
                ('reason', models.CharField(blank=True, default='', max_length=1000)),
                ('approved', models.BooleanField(blank=True, default=False)),
                ('assigned_date', models.DateField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='PinkSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='', max_length=200)),
                ('student_id', models.CharField(default='', max_length=200)),
                ('date', models.DateField(default=datetime.datetime(2024, 3, 9, 13, 26, 36, 266226, tzinfo=datetime.timezone.utc))),
                ('pinkslip_id', models.CharField(blank=True, default='', max_length=200)),
                ('reason', models.CharField(blank=True, default='', max_length=1000)),
                ('approved', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
