# Generated by Django 5.0.3 on 2024-03-09 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkslips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=200)),
                ('insurance_details', models.CharField(max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField()),
                ('expiration_date', models.DateField()),
                ('supplier_information', models.CharField(max_length=200)),
                ('inventory_type', models.CharField(choices=[('medicine', 'Medicine'), ('equipment', 'Equipment')], default='medicine', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='appointments',
            name='assigned_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 9, 15, 11, 44, 346077, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='preferred_end_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 15, 11, 44, 346027, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='preferred_start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 15, 11, 44, 346008, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pinkslip',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 15, 11, 44, 345492, tzinfo=datetime.timezone.utc)),
        ),
    ]
